name: Deploy Streamlit App with Cloudflare Tunnel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Set up Origin Certificate
        run: |
          echo "${{ secrets.CLOUDFLARED_ORIGIN_CERT }}" > ~/.cloudflared/cert.pem

      - name: Verify cloudflared Installation
        run: |
          cloudflared --version

      - name: Start Streamlit App
        run: |
          nohup streamlit run web/Home.py &

      - name: Run Cloudflare Tunnel
        run: |
          cloudflared tunnel --config config.yml run streamlit
